"$schema" = '~/.config/ironbar/schema.json'
position = "top"
height = 32
start = []
center = []

margin.top = 5
margin.bottom = 5
margin.left = 5
margin.right = 5

layer = "overlay"
exclusive_zone = true
popup_gap = 5
icon_theme = "Breeze"

[[end]]
type = "sys_info"
format = [
	" {cpu_percent}% | {temp_c:k10temp-Tccd1}°C",
	" {memory_used} / {memory_total} GB ({memory_percent}%)",
	"| {swap_used} / {swap_total} GB ({swap_percent}%)",
	"󰋊 {disk_used:/} / {disk_total:/home/dex} GB ({disk_percent:/}%)",
	"󰓢 {net_down:enp39s0} / {net_up:enp39s0} Mbps",
	"󰖡 {load_average:1} | {load_average:5} | {load_average:15}",
	"󰥔 {uptime}",
]

[[end]]
type = "custom"
class = "power-menu"
tooltip = "Up: {{30000:uptime -p | cut -d ' ' -f2-}}"

[[end.bar]]
type = "button"
name = "power-btn"
label = ""
on_click = "popup:toggle"

[[end.popup]]
type = "box"
orientation = "vertical"

[[end.popup.widgets]]
type = "label"
name = "header"
label = "Power menu"

[[end.popup.widgets]]
type = "box"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!shutdown now"

[[end.popup.widgets.widgets]]
type = "button"
class = "power-btn"
label = "<span font-size='40pt'></span>"
on_click = "!reboot"

[[end.popup.widgets]]
type = "label"
name = "uptime"
label = "Uptime: {{30000:uptime -p | cut -d ' ' -f2-}}"

[[end]]
type = "clock"

[[end]]
type = "tray"
