[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"


[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Yank image and copy it to clipboard"
