[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
sort_translist = false
linemode = "permissions"
show_hidden = false
show_symlink = true
mouse_events = ['click', 'scroll', 'touch']

[preview]
wrap = 'no'
tab_size = 4
image_delay = 100
image_filter = 'lanczos3'
image_quality = 60

[opener]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', orphan = true, for = "unix" }]
